openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://stream-orders-api-sandbox.herokuapp.com/client_api/v1/'
info:
  description: |
    Version 1 - Contains ability to create quotes and view the pricing on the different providers
    sds
  version: 1.0.0
  title: This the the Stream API to be able to create quotes
  contact:
    email: developers@vatitstream.com
tags:
  - name: Initial Authentication
    description: Used to generate the bearer token
  - name: Flow requests
    description: General flow requests where the logic sits
  - name: Static Data
    description: Used for lookup of information
security:
  - bearerAuth: []
paths:
  /auth/sign_in:
    post:
      tags:
        - Initial Authentication
      summary: Create a JWT token for subsequent requests
      description: |
        Post in the username and password credentials to receive a JWT token to be used for authentication. <br/><br/>
        Once you have done this and received the response token, you may use it in the Header of subsequent requests for authentication:<br/><br/>
        `Authorization: Bearer {INSERT TOKEN HERE}` <br/><br/>
        The token will last for 6 hours or until midnight (SAST), whichever is longer, after which a new token will need to be generated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth'
      security: []
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_response'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /countries:
    get:
      parameters:
        - in: query
          name: show_all
          schema:
            type: boolean
            enum:
              - true
              - false
          description: Select true not to paginate the results.
      summary: Countries
      tags:
        - Static Data
      responses:
        '200':
          description: fetch all the 'country' items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/country'
  /currencies:
    get:
      summary: Currencies
      tags:
        - Static Data
      responses:
        '200':
          description: fetch all the 'currency' items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/currency'
  /purpose_of_shipments:
    get:
      summary: Purpose of Shipment (or IncoTerms)
      tags:
        - Static Data
      responses:
        '200':
          description: fetch all the 'purpose_of_shipment' items. Also known as the IncoTerms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/purpose_of_shipment'
  /quotes:
    post:
      tags:
        - Flow requests
      summary: Quote - Create
      operationId: createQuote
      description: |
        Create a quote on the system, which will then have several estimates
        associated to it on which an order can be placed. These are called estimates as the final costs will be determined when the undelying provider measures the packages and provides a final offical billable weight. This (the billable) is regularly incorrectly stated by clients
      responses:
        '201':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quote_response'
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quote'
        description: Inventory item to add
  '/quotes/{id}':
    get:
      tags:
        - Flow requests
      summary: Quote - GET
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: id of an existing quote
      operationId: getQuote
      description: |
        This will return the available pricing options (estimates) for the quote details supplied
      responses:
        '200':
          description: get a quote that was created recently
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quote_response'
        '400':
          description: bad input parameter
components:
  schemas:
    auth_response:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzadfaskdjLKSAJSLdkoIASjdlaksjoj
    auth:
      type: object
      properties:
        api_user:
          type: object
          properties:
            email:
              type: string
              example: email@email.com
            password:
              type: string
              example: p@55w0rd
    country:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Serbia
        iso_code_2:
          type: string
          example: RS
    currency:
      type: object
      properties:
        id:
          type: string
          example: GBP
        name:
          type: string
          example: Pound
    dangerous_goods:
      required:
        - un_code
      properties:
        un_code:
          type: string
          example: UN3090
    estimate:
      type: object
      properties:
        shipping_company:
          type: string
          example: FedEx USA
        shipping_service:
          type: string
          example: Express Priority
        estimate_id:
          type: integer
          example: 55788
        quote_expired:
          type: boolean
          example: false
        line_items:
          type: array
          items:
            $ref: '#/components/schemas/line_item'
        transit_detail:
          type: object
          properties:
            min_transit_time:
              type: integer
              example: 1
            max_transit_time:
              type: integer
              example: 1
            transit_time_note:
              type: string
              example: clearance delay possible
        billable_weight:
          type: object
          properties:
            metric:
              type: object
              properties:
                packages:
                  type: integer
                  example: '2,'
                mass_unit:
                  type: string
                  example: kg
                distance_unit:
                  type: string
                  example: cm
                volumetric_weight:
                  type: number
                  example: 50
                weight:
                  type: number
                  example: 100
                billable_weight:
                  type: number
                  example: 100
            imperial:
              type: object
              properties:
                packages:
                  type: integer
                  example: 2
                mass_unit:
                  type: string
                  example: lb
                distance_unit:
                  type: string
                  example: inches
                volumetric_weight:
                  type: number
                  example: 110.231
                weight:
                  type: number
                  example: 220.462
                billable_weight:
                  type: number
                  example: 220.462
    hs_code:
      type: object
      required:
        - code
        - cost
        - description
        - quantity
        - weight
        - country_id
      properties:
        code:
          type: string
          example: 100322
        cost:
          type: string
          example: 100
        description:
          type: string
          example: networking equipment
        quantity:
          type: integer
          example: 5
        weight:
          type: number
          example: 1.1
        eccn:
          type: string
          format: 5 digit number
          example: 12345
        country_id:
          type: integer
          format: (country of origin of goods)
          example: 5
    line_item:
      type: object
      properties:
        description:
          type: string
          example: Fuel Surcharge
        cost:
          type: number
          example: 469.95
        invoice_section:
          type: string
          example: Express Rate Fees
        currency_id:
          type: string
          example: USD
    package:
      type: object
      required:
        - weight
        - width
        - height
        - length
      properties:
        weight:
          type: number
          example: 5.5
        width:
          type: number
          example: 5.5
        height:
          type: number
          example: 5.5
        length:
          type: number
          example: 5.5
    purpose_of_shipment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        description:
          type: string
          example: Cost Insurance & Freight
        code:
          type: string
          example: CIF
    quote_response:
      type: object
      properties:
        id:
          type: integer
          example: 1
        estimates:
          type: array
          items:
            $ref: '#/components/schemas/estimate'
        origin_country_id:
          type: integer
          example: 1
        destination_country_id:
          type: integer
          example: 2
        value_of_goods:
          type: string
          format: Money
          example: '600.00'
        value_of_goods_currency_id:
          type: string
          format: 3 Digit Currency Code
          example: ZAR
        purpose_of_shipment_id:
          type: integer
          example: 8
        is_document:
          type: boolean
          example: true
        is_stackable:
          type: boolean
          example: true
        is_shipment_protection_required:
          type: boolean
          example: true
        dangerous_goods_present:
          type: boolean
          example: false
        distance_unit:
          type: string
          format: cm/in
          example: cm
        mass_unit:
          type: string
          format: kg/lb
          example: kg
        iata_approved:
          type: boolean
          example: true
        packages:
          type: array
          items:
            $ref: '#/components/schemas/package'
        dangerous_goods:
          type: array
          items:
            $ref: '#/components/schemas/dangerous_goods'
        hs_codes:
          type: array
          items:
            $ref: '#/components/schemas/hs_code'
    quote:
      type: object
      required:
        - origin_country_id
        - destination_country_id
        - is_document
        - is_stackable
        - purpose_of_shipment_id
        - is_shipment_protection_required
        - value_of_goods
        - value_of_goods_currency_id
        - mass_unit
        - distance_unit
        - iata_approved
        - packages
        - dangerous_goods
        - hs_codes
      properties:
        origin_country_id:
          type: integer
          example: 1
        destination_country_id:
          type: integer
          example: 2
        value_of_goods:
          type: string
          format: Money
          example: '600.00'
        value_of_goods_currency_id:
          type: string
          format: 3 Digit Currency Code
          example: ZAR
        purpose_of_shipment_id:
          type: integer
          example: 8
        is_document:
          type: boolean
          example: true
        is_stackable:
          type: boolean
          example: true
        is_shipment_protection_required:
          type: boolean
          example: true
        dangerous_goods_present:
          type: boolean
          example: false
        distance_unit:
          type: string
          format: cm/in
          example: cm
        mass_unit:
          type: string
          format: kg/lb
          example: kg
        iata_approved:
          type: boolean
          example: true
        packages:
          type: array
          items:
            $ref: '#/components/schemas/package'
        dangerous_goods:
          type: array
          items:
            $ref: '#/components/schemas/dangerous_goods'
        hs_codes:
          type: array
          items:
            $ref: '#/components/schemas/hs_code'
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
