openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: "https://stream-orders-api-sandbox.herokuapp.com/client_api/v1/"
  - description: Local SwaggerHub API Auto Mocking
    url: "http://localhost:4000/client_api/v1/"
info:
  description: |
    <b>Version 1.4.0 (2020-04-09) - API Documentation for Stream</b>
    <ul>
      <li>Certain endpoints may be subject to rate limiting. In this case, a response code of 429 will be returned. See POST orders.</li>
      <li>Export permits endpoint exposed. See static data section.</li>
      <li>Only one order will be able to be placed on an quote_estimate_id, once a quote_estimate_id has an order associated to it you will need to request a new quote and get a new estimate</li>
    </ul>
    <br>
  version: 1.4.0
  title: >-
    Stream API
  contact:
    email: developers@vatitstream.com
tags:
  - name: Initial Authentication
    description: Used to generate the bearer token
  - name: Quote
    description: The flow for creating and fetching quotes
  - name: Order
    description: >-
      The flow for creating and fetching orders along with additional operations
      which can be performed on orders
  - name: Static Data
    description: Used for lookup of information
security:
  - bearerAuth: []
