openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://stream-orders-api-sandbox.herokuapp.com/client_api/v1/'
info:
  description: >
    Version 1 - Contains ability to create quotes and view the pricing on the
    different providers

    sds
  version: 1.0.0
  title: This the the Stream API to be able to create quotes
  contact:
    email: developers@vatitstream.com
tags:
  - name: Initial Authentication
    description: Used to generate the bearer token
  - name: Flow requests
    description: General flow requests where the logic sits
  - name: Static Data
    description: Used for lookup of information
security:
  - bearerAuth: []
